name: order_tracker_zen
description: This is a simple order tracking UI Produly made by Team Zenzzen

version: 0.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

homepage: https://zenzzen.com/open-source-development/order-tracker-zen
