name: order_tracker_zen
description: This is a Popular, Simple and Easy to use Flutter Order Tracking UI that Proudly made by Team Zenzzen

version: 1.0.0+4

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

homepage: https://github.com/zenzzenpl/order_tracker_zen
